### PR TITLE
Fix #28: implement simple sync() 

### LINKED ISSUE #28: Add sync() method
**Goal**

* Maintain local storage (#27) up-to-date (we will want to call `.sync()` regularly, from a timer or on push notification)
* Fetch partial changes instead of whole changeset

**Behaviour**

(part of this behaviour was implemented in #27 in `.get()`, it will have to be moved to this new `.sync()`)

* In `.get()`, if storage is empty for this bucket/collection, call `.sync()`, and then return records

During sync:

* If storage is empty for this bucket/collection, fetch from `.../changeset`, store locally, validate signature, and return records
* Otherwise, obtain current remote timestamp of collection from server (see #27)
* If remote timestamp is same as local, do nothing. 
* If remote timestamp is different than local, fetch *partial* changeset with `?_since=<local-timestamp>&_expected=<remote-timestamp>`, and import the obtained changes (see below). Validate the signature (see below), and return records.

Import changes:

* If remote record has field `deleted: true` then delete the local record (use `id` field)
* Otherwise overwrite the local record

Validate signature:

* After importing the partial changes, we want to make sure that the results (old local records - deleted records + newly imported changes) match the signature.
* If signature verification fails, we wipe the local DB, refetch the whole changeset (no `_since`), import all records, and verify signature again.
* If signature verification fails again after this retry, `sync()` will return a synchronization error

**Notes**

* The `store()` method of storage will need to be expanded to have support the deletion of records, and possible have a `clear` option to wipe all the local records before storing the new ones. It will be used in the *signature retry* situation described above.
* The code should limit the number of calls to `retrieve()` / `store()` (keep in mind that storage is extreeeeemely slow)
* [See JS implementation of store()](https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/services/settings/Database.jsm#79-161)
* [See JS implementation of sync()](https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/services/settings/RemoteSettingsClient.jsm#835-960). Warning: it has behaviours that we won't implement here (yet), as for example, verifying signature of local data before retrying etc.

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #28

### CODE REVIEW

File: src/client.rs [hunk 1]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+            }
+        };
 
-        if let Some(collection) = stored {
+        if let Some(ref collection) = stored {
             let up_to_date = collection.timestamp == remote_timestamp;
             if up_to_date && self.verifier.verify(&collection).is_ok() {
                 debug!("Local data is up-to-date and valid.");
-                return Ok(collection.records);
+                return Ok(collection.to_owned());
```
Comment (smarnach) [inline src/client.rs:367]: This reallocates on copied the whole collection, which seems unnecessary. Maybe use
```suggestion
                return Ok(stored.unwrap());
```
instead? Unwrapping is fine here, since we already know that `stored` is `Some(_)`.

File: src/client.rs [hunk 2]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+
+        debug!(
+            "Apply {} changes to {} local records",
+            changeset.changes.len(),
+            local_records.len()
+        );
+        let merged = merge_changes(local_records.to_vec(), changeset.changes);
+
+        let collection = Collection {
+            bid: self.bucket_name.to_owned(),
```
Comment (smarnach) [inline src/client.rs:393]: I think it's a lot more common to use `clone()` in cases like this, since it captures the intention better. You already have an owned string, and you want to clone it. (This is a purely stylistic difference. The resulting code is identical.)

File: src/client.rs [hunk 3]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+            Some(remote_timestamp),
+            local_timestamp,
+        )?;
+
+        debug!(
+            "Apply {} changes to {} local records",
+            changeset.changes.len(),
+            local_records.len()
+        );
+        let merged = merge_changes(local_records.to_vec(), changeset.changes);
```
Comment (smarnach) [inline src/client.rs:390]: `to_vec()` unnecessarily copied the data here. I think you can simply remove it.

File: src/client.rs [hunk 4]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+
+fn merge_changes(
+    local_records: Vec<KintoObject>,
+    remote_changes: Vec<KintoObject>,
+) -> Vec<KintoObject> {
+    // Merge changes by record id and delete tombstones.
+    let mut local_by_id: HashMap<String, KintoObject> = HashMap::new();
+    for record in local_records {
+        local_by_id.insert(record["id"].to_string(), record);
+    }
```
Comment (smarnach) [inline src/client.rs:419]: Another common way of writing this:
```suggestion
    let mut local_by_id: HashMap<String, KintoObject> = local_records
        .into_iter()
        .map(|record| (record["id"].to_string(), record))
        .collect();
```
This version sometimes allows the compiler to optimize the code better, e.g. by only requiring a single allocation, since the size of the `HashMap` is known from the get-go. Dynamically growing a `HashMap` generally takes multiple allocations.

The id is serialized to JSON again here. I don't think that's a problem – it just feels a bit unnatural to me.

File: src/client.rs [hunk 5]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+    for change in remote_changes.iter().rev() {
+        let id = change["id"].to_string();
+        if change
+            .get("deleted")
+            .unwrap_or(&json!(false))
+            .as_bool()
+            .unwrap_or(false)
```
Comment (smarnach) [inline src/client.rs:426]: Here's a version that provides the default value only once:
```suggestion
            .map(|v| v.as_bool())
            .flatten()
            .unwrap_or(false)
```
Not sure whether that's easier to read, though.

File: src/client.rs [hunk 6]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+        {
+            local_by_id.remove(&id);
+        } else {
+            local_by_id.insert(id, change.to_owned());
```
Comment (smarnach) [inline src/client.rs:430]: You can remove `to_owned()` and with it an allocation for each record if you use `into_iter()` in the for loop. Since this function takes ownership of `remote_changes`, you can move the records out, and don't need to clone them.

File: src/client.rs [hunk 7]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
+        }
     }
+
+    local_by_id
+        .values()
+        .map(|v| v.to_owned())
+        .collect::<Vec<KintoObject>>()
+        .to_vec()
```
Comment (smarnach) [inline src/client.rs:438]: This is another unnecessary clone. You already collect into a vector, so you don't need `to_vec()` here.

**Review by smarnach — COMMENTED** [review]
Nice! I've added a bunch of suggestions – I didn't see any major issues, so I commented on minor nits and style issues. I'll take a closer look at the test code tomorrow.

I really enjoy looking at Rust code as part of my actual job. :)

**Comment by smarnach** [comment]
Another issue I noticed when reading the existing code is that the `FileStorage` may map different collections to the same filename on disk. Probably not a problem in practice, so I won't file an issue for it.

File: src/client.rs [hunk 8]
```diff
@@ -285,71 +280,181 @@ impl Client {
...
     /// # Errors
     /// If an error occurs while fetching or verifying records, a [`ClientError`] is returned.
     pub fn get(&mut self) -> Result<Vec<KintoObject>, ClientError> {
         let storage_key = format!("{}/{}:collection", self.bucket_name, self.collection_name);
+
         debug!("Retrieve from storage with key={:?}", storage_key);
         let stored_bytes: Vec<u8> = self
             .storage
             .retrieve(&storage_key)
             .unwrap_or(None)
```
[the remark this answers is not in the document]
Comment (leplatrem) [reply src/client.rs:356]: I'll open an issue, I realize there's a lot of work concerning Error «bubbling»

**Review by smarnach — APPROVED** [review]
The test code is looking great as well, so I think this is good to go.
