### PR TITLE
Fix #27: add Storage feature

### LINKED ISSUE #27: Add storage feature
**Goal**

* Add «cache» (or storage) feature to `.get()`

This will be pave the way for synchronization features. 

**Behaviour**

* If storage is empty for this bucket/collection, fetch from `.../changeset`, validate signature, store locally, and return records
* Otherwise, obtain current remote timestamp of collection from server (done in #26)
* If remote timestamp is different than local, fetch, validate signature, overwrite local existing data and return records
* If remote timestamp is same as local, validate signature and return records. If validating signature fails, fetch, validate, overwrite, and return records.

**Definition of done**

* A storage abstraction (pluggable) with a default implementation. This default implementation could be very «stupid» (eg. store as folders `{bucket}/{collection}.json`)
* Unit tests should cover almost 100% of situations
* Documentation etc.

**Notes**

* This storage abstraction could take `(bucket, collection)` as constructor and have only two methods (`store(metadata, timestamp, records)`  and `retrieve() -> {metadata, timestamp, records}`)
* When adding synchronization **later**, instead of fetching and overwriting everything locally, we'll fetch partial changes from `/changeset?_since=<local-timestamp>` and add the necessary complexity in the storage abstraction (tombstones, etc).
* We could follow the pattern of #37, where a dummy storage is a no-op, have a storage that writes files on disk, and choose storage feature from config (in the future we could have storage implementations in DB, indexeddb, rkv, ...)

### PR DESCRIPTION
**Pull request by Vishwa-Mozilla**
Fix #27

### CODE REVIEW

File: src/client/storage.rs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+/// # How can I implement ```RemoteStorage```?
+/// ```rust
+/// # use remote_settings_client::{SignatureError, Verification};
+/// # use remote_settings_client::client::Collection;
+/// struct MyStore {}
+///
+/// impl RemoteStorage for MyStore {
+///     fn store(&self, record: serde_json::Value) -> Result<(), RemoteStorageError> {
+///         Ok(())
+///     }
```
Comment (leplatrem) [inline src/client/storage.rs:17]: mention `retrieve` maybe? :)

File: src/client/storage.rs [hunk 2]
```diff
@@ -0,0 +1,52 @@
+
+pub mod default_cache;
+
+/// A trait for giving a type a custom cache storage implementation
+///
+/// Sometimes, you want to use your own cache implementation to store records retrieved from the remote-settings server
```
Comment (leplatrem) [inline src/client/storage.rs:6]: Since we provide a dumb storage implementation, we'll always want to have our own ;)

File: src/client/storage.rs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    /// # Errors
+    /// If an error occurs while storing or retrieving, ```RemoteStorageError``` is returned
+    fn store(&self, key: &str, value: serde_json::Value) -> Result<(), RemoteStorageError>;
+
+
+    /// Retrieve value mapping to the key
+    /// 
+    /// If key cannot be 
+    fn retrieve(&self, key:&str) -> Result<serde_json::Value, RemoteStorageError>;
+}
```
Comment (leplatrem) [inline src/client/storage.rs:34]: I think Nick was suggesting a JSON blob. Maybe not a server JSON value.

File: src/client.rs [hunk 4]
```diff
@@ -157,6 +170,48 @@ impl Client {
...
+            remote_timestamp,
+        )?;
+
+        debug!("changeset.metadata {}", serde_json::to_string_pretty(&changeset_response.metadata)?);
+
+        let collection: Collection = self.create_collection_from_response(changeset_response);
+        self.verifier.verify(&collection)?;
+
+        // before returning records, we want to override it into the cache
+        self.cache.store(&format!("{}/{}", collection.bid, collection.cid), json!(collection.records))?;
```
Comment (leplatrem) [inline src/client.rs:194]: The key should contain the type of data. For example `{bid}/{cid}:records`

Comment (leplatrem) [reply src/client.rs:194]: Also, I think the storing should be done in the same place as retrieving (even if it means to have repeated calls to `self.cache.store()`

File: src/client.rs [hunk 5]
```diff
@@ -175,32 +230,45 @@ impl Client {
...
+        // If storage is empty for this bucket/collection, fetch from .../changeset, validate signature, store locally, and return records
+        // Otherwise, obtain current remote timestamp of collection from server (done in #26)
+        // If remote timestamp is different than local, fetch, validate signature, overwrite local existing data and return records
+        // If remote timestamp is same as local, validate signature and return records. If validating signature fails, fetch, validate, overwrite, and return records.
+
+        let key = format!("{}/{}", self.bucket_name, self.collection_name);
+        match self.cache.retrieve(&key) {
+            Ok(value) => {
+                // convert JSON object to LatestChangeResponse object
+                let cached_change_response: ChangesetResponse = serde_json::from_value(value)?;
```
Comment (leplatrem) [inline src/client.rs:243]: I'm confused. What do you store in the cache? The changeset response or the list of records?

File: src/client/storage/default_cache.rs [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+    std::fs::OpenOptions,
+};
+
+pub struct DefaultCache {}
+
+impl RemoteStorage for DefaultCache {
+    fn store(&self, key: &str, value: Value) -> Result<(), RemoteStorageError> {
+        debug!("default cache store key={},value={}", key, value);
+
+        let file_name = &format!("{}.txt", key);
```
Comment (leplatrem) [inline src/client/storage/default_cache.rs:17]: There is no escaping necessary here? Like `..` or `/` ?

File: src/client/storage/default_cache.rs [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+        let path = Path::new(file_name);
+        let display = path.display();
+
+        // Open the path in read-only mode, returns `io::Result<File>`
```
Comment (leplatrem) [inline src/client/storage/default_cache.rs:21]: `.write(true)` does not sound like read-only ;)

File: src/client/storage/default_cache.rs [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+                file.write_all(content)?;
+                return Ok(())
+            },
+        };
+    }
+
+    fn retrieve(&self, key: &str) -> Result<Value, RemoteStorageError> {
+        debug!("default cache retrieve key={}", key);
+
+        let file_name = &format!("{}.txt", key);
```
Comment (leplatrem) [inline src/client/storage/default_cache.rs:42]: I would either not put any file extension, or `.bin`

File: src/client/storage/default_cache.rs [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+        let path = Path::new(file_name);
+
+        let display = path.display();
+
+        let mut file = match OpenOptions::new().read(true).write(false).open(path) {
+            Err(why) => {
+                info!("couldn't open or create {}: {}", display, why);
```
Comment (leplatrem) [inline src/client/storage/default_cache.rs:49]: The opening should not try to create the file, you can adjust the error message

File: src/client/storage/default_cache.rs [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+            },
+            Ok(file) => file,
+        };
+
+        // Read the file contents into a string, returns `io::Result<usize>`
+        let mut s = String::new();
+        match file.read_to_string(&mut s) {
+            Err(why) => {
+                info!("couldn't read {}: {}", display, why);
+                return Err(RemoteStorageError::DoesNotExistError {name: why.to_string()});
```
Comment (leplatrem) [inline src/client/storage/default_cache.rs:60]: At this point, it shouldn't be a `DoesNotExistError` but a `ReadError`, no?

File: src/client.rs (hunk 5 above)
Comment (Vishwa-Mozilla) [reply src/client.rs:243]: the changeset response

File: src/client/storage/default_cache.rs (hunk 7 above)
Comment (Vishwa-Mozilla) [reply src/client/storage/default_cache.rs:21]: lol, I forgot to remove the comment; its supposed to have write permissions :)

File: src/client/storage/default_cache.rs (hunk 8 above)
Comment (Vishwa-Mozilla) [reply src/client/storage/default_cache.rs:42]: okay

File: src/client/storage.rs (hunk 3 above)
Comment (Vishwa-Mozilla) [reply src/client/storage.rs:34]: how about I just send a string as value as well and I can convert it back to JSON when retrieved

Comment (ncalexan) [reply src/client/storage.rs:34]: Yes: something opaque.

File: src/client/storage.rs [hunk 11]
```diff
@@ -0,0 +1,52 @@
...
+    /// fetched from server
+    ///
+    /// # Errors
+    /// If an error occurs while storing or retrieving, ```RemoteStorageError``` is returned
+    fn store(&self, key: &str, value: serde_json::Value) -> Result<(), RemoteStorageError>;
+
+
+    /// Retrieve value mapping to the key
+    /// 
+    /// If key cannot be
```
Comment (ncalexan) [inline src/client/storage.rs:32]: nit: complete this comment.

File: src/client.rs [hunk 12]
```diff
@@ -157,6 +170,48 @@ impl Client {
...
+        let expected = get_latest_change_timestamp(
+            &self.server_url,
+            &self.bucket_name,
+            &self.collection_name,
+        )?;
+        
+        Ok(expected)
+    }
+
+    fn create_collection_from_response(&self, change_set_response: ChangesetResponse) -> Collection {
```
Comment (ncalexan) [inline src/client.rs:208]: why is it `change_set_response` in snake-case but `ChangesetResponse` in camel-case?  Those don't line up.

File: src/client/storage.rs [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+    ///
+    /// # Errors
+    /// If an error occurs while storing or retrieving, ```RemoteStorageError``` is returned
+    fn store(&self, key: &str, value: serde_json::Value) -> Result<(), RemoteStorageError>;
+
+
+    /// Retrieve value mapping to the key
+    /// 
+    /// If key cannot be 
+    fn retrieve(&self, key:&str) -> Result<serde_json::Value, RemoteStorageError>;
```
Comment (ncalexan) [inline src/client/storage.rs:33]: There's a difference between error (disk doesn't exist) and no cache entry.  Make this `Result<Option<T>, ...>`.

File: src/client/storage.rs (hunk 1 above)
Comment (Vishwa-Mozilla) [reply src/client/storage.rs:17]: done

File: src/client/storage/default_cache.rs (hunk 9 above)
Comment (Vishwa-Mozilla) [reply src/client/storage/default_cache.rs:49]: done
